-- Script per la creazione dello schema del database H2 per GymPal

-- Creazione tabella DIPENDENTI (se non esiste)
CREATE TABLE IF NOT EXISTS DIPENDENTI (
    STAFF_ID VARCHAR(50) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    COGNOME VARCHAR(50) NOT NULL,
    CONTATTO VARCHAR(100) NOT NULL,
    PRIMARY KEY (STAFF_ID)
);

-- Creazione tabella CLIENTI (se non esiste)
CREATE TABLE IF NOT EXISTS CLIENTI (
    CF VARCHAR(16) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    COGNOME VARCHAR(50) NOT NULL,
    SESSO CHAR(1) NOT NULL,
    FLAG_MINOR TINYINT NOT NULL, 
    CONTATTO VARCHAR(100) NOT NULL,
    ABBONAMENTO VARCHAR(20) NOT NULL,
    PRIMARY KEY (CF)
);

-- Creazione tabella CALENDARIO (se non esiste)
CREATE TABLE IF NOT EXISTS CALENDARIO (
    NOME_EVENTO VARCHAR(100) NOT NULL,
    DATA_EVENTO DATE NOT NULL,
    MESSAGGIO TEXT NOT NULL, 
    DESTINATARIO_MESSAGGIO VARCHAR(100) NOT NULL,
    PRIMARY KEY (NOME_EVENTO, DATA_EVENTO)
);

-- Tabella per memorizzare informazioni sulla sincronizzazione
CREATE TABLE IF NOT EXISTS SINCRO_INFO (
    CHIAVE VARCHAR(255) PRIMARY KEY,
    VALORE VARCHAR(255) NOT NULL
);
