-- Script per la creazione dello schema del database H2 per GymPal

-- Creazione tabella DIPENDENTI (se non esiste)
CREATE TABLE IF NOT EXISTS DIPENDENTI (
    STAFF_ID VARCHAR(50) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    COGNOME VARCHAR(50) NOT NULL,
    CONTATTO VARCHAR(100) NOT NULL,
    PRIMARY KEY (STAFF_ID)
);

-- Creazione tabella CLIENTI (se non esiste)
CREATE TABLE IF NOT EXISTS CLIENTI (
    CF VARCHAR(16) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    COGNOME VARCHAR(50) NOT NULL,
    SESSO CHAR(1) NOT NULL,
    FLAG_MINOR BOOLEAN NOT NULL,
    CONTATTO VARCHAR(100) NOT NULL,
    ABBONAMENTO VARCHAR(50) NOT NULL, 
    INIZIO_ABBONAMENTO DATE,         
    FINE_ABBONAMENTO DATE,           
    PAGAMENTO_EFFETTUATO BOOLEAN NOT NULL, 
    COMPOSIZIONE_ABBONAMENTO VARCHAR(255), 
    PRIMARY KEY (CF)
);

-- Creazione tabella CALENDARIO (se non esiste)
CREATE TABLE IF NOT EXISTS CALENDARIO (
    NOME_EVENTO VARCHAR(100) NOT NULL,
    DATA_EVENTO DATE NOT NULL,
    ORA_INIZIO TIME NOT NULL,
    ORA_FINE TIME NOT NULL,
    MESSAGGIO TEXT NOT NULL,
    DESTINATARIO_MESSAGGIO VARCHAR(100) NOT NULL,
    PRIMARY KEY (NOME_EVENTO, DATA_EVENTO, ORA_INIZIO, ORA_FINE)
);

-- Creazione tabella TURNI (se non esiste)
CREATE TABLE IF NOT EXISTS TURNI (
    DATA DATE NOT NULL,
    REC_MAT VARCHAR(50),
    REC_POM VARCHAR(50),
    PT_MAT VARCHAR(50),
    PT_POM VARCHAR(50),
    PRIMARY KEY (DATA),
    FOREIGN KEY (REC_MAT) REFERENCES DIPENDENTI(STAFF_ID),
    FOREIGN KEY (REC_POM) REFERENCES DIPENDENTI(STAFF_ID),
    FOREIGN KEY (PT_MAT) REFERENCES DIPENDENTI(STAFF_ID),
    FOREIGN KEY (PT_POM) REFERENCES DIPENDENTI(STAFF_ID)
);

-- Creazione tabella SESSIONI_CORSI (se non esiste)
CREATE TABLE IF NOT EXISTS SESSIONI_CORSI (
    ID_SESSIONE VARCHAR(50) NOT NULL,
    STAFF_ID VARCHAR(50) NOT NULL,
    DATA DATE NOT NULL,
    FASCIA_ORARIA VARCHAR(11) NOT NULL,
    NUM_ISCRITTI INT NOT NULL,
    PRIMARY KEY (ID_SESSIONE),
    FOREIGN KEY (STAFF_ID) REFERENCES DIPENDENTI(STAFF_ID)
);

-- Creazione tabella PARTECIPAZIONI_CORSI (se non esiste)
CREATE TABLE IF NOT EXISTS PARTECIPAZIONI_CORSI (
    CF VARCHAR(16) NOT NULL,
    ID_SESSIONE VARCHAR(50) NOT NULL,
    PRIMARY KEY (CF, ID_SESSIONE),
    FOREIGN KEY (CF) REFERENCES CLIENTI(CF),
    FOREIGN KEY (ID_SESSIONE) REFERENCES SESSIONI_CORSI(ID_SESSIONE)
);

-- Creazione tabella DATE_SCONTI (se non esiste)
CREATE TABLE IF NOT EXISTS DATE_SCONTI (
    NOME_SCONTO VARCHAR(100) NOT NULL,
    DATA_SCONTO DATE NOT NULL,
    AMOUNT_SCONTO DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY (NOME_SCONTO)
);

-- Creazione tabella APPUNTAMENTI_PT (se non esiste)
CREATE TABLE IF NOT EXISTS APPUNTAMENTI_PT (
    CF VARCHAR(16) NOT NULL,
    STAFF_ID VARCHAR(50) NOT NULL,
    DATA DATE NOT NULL,
    FASCIA_ORARIA VARCHAR(11) NOT NULL,
    PRIMARY KEY (CF, STAFF_ID, DATA, FASCIA_ORARIA),
    FOREIGN KEY (CF) REFERENCES CLIENTI(CF),
    FOREIGN KEY (STAFF_ID) REFERENCES DIPENDENTI(STAFF_ID)
);

-- Tabella per memorizzare informazioni sulla sincronizzazione
CREATE TABLE IF NOT EXISTS SINCRO_INFO (
    CHIAVE VARCHAR(255) PRIMARY KEY,
    VALORE VARCHAR(255) NOT NULL
);